updateUrls:
  - 'http://kokakiwi.github.com/BukkitUpdater/updateList.xml'
  - 'http://www.minerepo.tk/repo.xml'
  - 'http://www.kokabsolu.com/updateList.xml'
bukkitCoreVersion: 'recommended'
updateTimer: 43200000